---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: passwords.secret.example.com
spec:
  group: secret.example.com
  names:
    kind: Password
    listKind: PasswordList
    plural: passwords
    singular: password
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.state
      name: State
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Password is the Schema for the passwords API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PasswordSpec defines the desired state of Password
            properties:
              caseSensitive:
                default: false
                type: boolean
              digit:
                default: 10
                minimum: 0
                type: integer
              disallowRepeat:
                default: false
                type: boolean
              length:
                default: 20
                minimum: 8
                type: integer
              symbol:
                default: 10
                minimum: 0
                type: integer
            required:
            - length
            type: object
          status:
            description: PasswordStatus defines the observed state of Password
            properties:
              state:
                description: Information about if Password is in-sync.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
